CREATE DATABASE SOCCER;

USE SOCCER;

SELECT * FROM MATCH_MAST;
SELECT * FROM MATCH_DETAILS;
SELECT * FROM SOCCER_COUNTRY;
SELECT * FROM PLAYER_MAST;
SELECT * FROM GOAL_DETAILS;
SELECT * FROM SOCCER_CITY;
SELECT * FROM SOCCER_VENUE;

-- 1. No of countries played in the EURO 2016 GAME 
SELECT COUNT(DISTINCT(TEAM_ID))
FROM PLAYER_MAST;

-- 2. 
SELECT COUNT(*) AS Number_Of_Matches_With_Result
FROM MATCH_MAST
WHERE  RESULTS IS NOT NULL;

-- 3. 
SELECT PLAY_DATE AS START_DATE
FROM MATCH_MAST
WHERE PLAY_DATE LIKE "%2016"
LIMIT 1;


-- 4. find out where the final match of the EURO cup was played Venue name - City 
SELECT V.VENUE_NAME, C.CITY
FROM SOCCER_VENUE AS V
JOIN 
SOCCER_CITY AS C
ON V.CITY_ID = C.ï»¿city_id
WHERE 
V.ï»¿venue_id = (SELECT VENUE_ID FROM MATCH_MAST WHERE PLAY_STAGE = "F");

--  5.the number of goals scored by each team in each match during normal play.
SELECT M.MATCH_NO, C.COUNTRY_NAME, M.GOAL_SCORE
FROM MATCH_DETAILS AS M
JOIN SOCCER_COUNTRY AS C
ON M.TEAM_ID = C.ï»¿country_id;


-- 6. count the number of goals scored by each player within a normal play schedule
SELECT P.PLAYER_NAME, COUNT(G.GOAL_ID)AS NO_OF_GOALS,C.COUNTRY_NAME
FROM PLAYER_MAST AS P
JOIN GOAL_DETAILS AS G
ON P.ï»¿player_id = G.PLAYER_ID
JOIN SOCCER_COUNTRY AS C
ON P.TEAM_ID = C.ï»¿country_id
WHERE G.GOAL_SCHEDULE = "NT"
GROUP BY P.PLAYER_NAME, C.COUNTRY_NAME
ORDER BY NO_OF_GOALS DESC;

-- 7. o find out who scored the most goals in the 2016 Euro Cup. 

SELECT P.PLAYER_NAME, C.COUNTRY_NAME, COUNT(G.GOAL_ID) AS NO_OF_GOALS
FROM PLAYER_MAST AS P
JOIN GOAL_DETAILS AS G
ON P.ï»¿player_id = G.PLAYER_ID
JOIN SOCCER_COUNTRY AS C
ON P.TEAM_ID = c.ï»¿country_id
GROUP BY P.PLAYER_NAME, C.COUNTRY_NAME
ORDER BY NO_OF_GOALS DESC;



-- 8.  find out which teams played the first match of the 2016 Euro Cup.
SELECT MATCH_NO, COUNTRY_NAME
FROM MATCH_DETAILS AS M
JOIN SOCCER_COUNTRY AS C
ON M.TEAM_ID = C.ï»¿country_id
WHERE match_no = 1;

-- 9. 
SELECT MAX(AUDENCE) FROM MATCH_MAST;

SELECT MATCH_NO, PLAY_STAGE, GOAL_SCORE, AUDENCE
FROM MATCH_MAST
WHERE AUDENCE IN
(
SELECT MAX(AUDENCE) FROM MATCH_MAST
);
SELECT*FROM PLAYER_MAST;

-- 10. the players who scored goals in each match. 
SELECT G.MATCH_NO, C.COUNTRY_NAME, P.PLAYER_NAME, COUNT(*)
FROM GOAL_DETAILS AS G
JOIN SOCCER_COUNTRY AS C
ON G.TEAM_ID = C.ï»¿country_id
JOIN PLAYER_MAST AS P
ON G.PLAYER_ID = P.ï»¿player_id
GROUP BY G.MATCH_NO, C.COUNTRY_NAME, P.PLAYER_NAME
ORDER BY G.MATCH_NO ASC;